//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LobsterWpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tortoisemerge")]
        public string DiffProgramName {
            get {
                return ((string)(this["DiffProgramName"]));
            }
            set {
                this["DiffProgramName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/mine:\"{0}\" /theirs:\"{1}\"")]
        public string DiffProgramArguments {
            get {
                return ((string)(this["DiffProgramArguments"]));
            }
            set {
                this["DiffProgramArguments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.html</string>
  <string>.txt</string>
  <string>.xml</string>
  <string>.xmls</string>
  <string>.xmlp</string>
  <string>.js</string>
  <string>.css</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DiffableExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DiffableExtensions"]));
            }
            set {
                this["DiffableExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources/Audio/success.wav")]
        public string SuccessSoundFile {
            get {
                return ((string)(this["SuccessSoundFile"]));
            }
            set {
                this["SuccessSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Resources/Audio/failure.wav")]
        public string FailureSoundFile {
            get {
                return ((string)(this["FailureSoundFile"]));
            }
            set {
                this["FailureSoundFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int BackupFileLifetimeDays {
            get {
                return ((int)(this["BackupFileLifetimeDays"]));
            }
            set {
                this["BackupFileLifetimeDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeleteBackupFiles {
            get {
                return ((bool)(this["DeleteBackupFiles"]));
            }
            set {
                this["DeleteBackupFiles"] = value;
            }
        }
    }
}
